version: "3"
services:
  backend:
    container_name: backend 
    build:
        context: ./server
    depends_on:
      - db  
    # volumes:
    #   - ./server:/app
    #   - /server/app/node_modules
    environment:  
      - MONGO_URL=mongodb://db:27017/marketings
    expose:
      - "3030"
    ports:
      - '3030:3030'

  db:
    container_name: db
    image: mongo
    hostname: mongo
    restart: always
    ports:
      - "27017:27017"
  client:
    build: client/
    network_mode: host
    ports:
      - "8080:8080"
    depends_on:
      - backend
